# Generated by Django 4.2.13 on 2024-08-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('tenderid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('subcatname', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('sdate', models.DateField()),
                ('edate', models.DateField()),
                ('tenderfilename', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=50)),
            ],
        ),
    ]
